### PR TITLE
Nav & Header UI

### PR DESCRIPTION
**Pull request by rfabricioflores**
- New logo
- Responsive nav and header
- Mobile menu

[Click here to see the video](https://cdnembed.netlify.app/nav-ui)

### CODE REVIEW

**Review by jakobpalmborg — CHANGES_REQUESTED** [review]
Great! Very nice! 

One thing that has changed is that the css for the movies don't work as it should. All movies are in one column in all screen sizes. It would be nice to fix this before merge.
image

Another thing that could be even better is the meny-list (filmer, salonger, restaurang, events, kontakt). When in small screen you can't see the whole meny.  Should we have it in a dropdown? Maybe in two rows? or vertical somehow. What do you think?
image

**Comment by MrFabri** [comment]
> Great! Very nice!
> 
> One thing that has changed is that the css for the movies don't work as it should. All movies are in one column in all screen sizes. It would be nice to fix this before merge. image
> 
> Another thing that could be even better is the meny-list (filmer, salonger, restaurang, events, kontakt). When in small screen you can't see the whole meny. Should we have it in a dropdown? Maybe in two rows? or vertical somehow. What do you think? image

Yes I forgot about this, imma fix it asap.

**Comment by rfabricioflores** [comment]
> One thing that has changed is that the css for the movies don't work as it should. All movies are in one column in all screen sizes. It would be nice to fix this before merge. 

Yes I forgot about this, imma fix it asap.

**Comment by rfabricioflores** [comment]
> Another thing that could be even better is the meny-list (filmer, salonger, restaurang, events, kontakt). When in small screen you can't see the whole meny. Should we have it in a dropdown? Maybe in two rows? or vertical somehow. What do you think?

A dropdown would probably have been too much, I think this is a simple and user-friendly solution 👍

**Comment by MrFabri** [comment]
> Great! Very nice!
> 
> One thing that has changed is that the css for the movies don't work as it should. All movies are in one column in all screen sizes. It would be nice to fix this before merge. image
> 
> Another thing that could be even better is the meny-list (filmer, salonger, restaurang, events, kontakt). When in small screen you can't see the whole meny. Should we have it in a dropdown? Maybe in two rows? or vertical somehow. What do you think? image

**Comment by rfabricioflores** [comment]
> > One thing that has changed is that the css for the movies don't work as it should. All movies are in one column in all screen sizes. It would be nice to fix this before merge.
> 
> Yes I forgot about this, imma fix it asap.

Fixed✅
image
image

**Pull request closed without merging**
